### ISSUE TITLE
Just realized I opened issues in the wrong repository

### ISSUE THREAD

**Issue by pkazemiuo** [pkazemiuo/Muslim_Integration#1]
Hi @AaronGullickson I have uploaded my introduction issue that I had with the header in GitHub. I realized I had previously submitted this issue in another repository so you may not have seen it.

**Comment by AaronGullickson** [comment]
Hi @pkazemiuo. Sorry for the delay in getting back to this. I fixed the header issues in your file in commit 004c8bd5f12d2ccbf7cec0c17c4627c5d7da6f43. Its important to keep all of the indentation that occurs there. You shouldn't need to mess with it anymore. 

Just pull in my changes and it should knit fine. I also knit to PDF and pushed the new PDF so you can see what it should look like.
