### ISSUE TITLE
Finished getting data and loading into R

### ISSUE THREAD

**Issue by pkazemiuo** [pkazemiuo/Muslim_Integration#2]
Hi @AaronGullickson, I've finished loading the raw data into R and I've added the data section to my R markdown as well. Thanks!

**Comment by AaronGullickson** [comment]
Hi @pkazemiuo. The description of the data is very thorough. However, your script for reading in the data does not work. There is no csv file in your input directory. The files containing the data and codebooks are zipped up and the data inside that is a stata DTA dataset not a CSV file. I wrote some better code for reading in the data with commit bac4a365482adba2b5d6b0f45d219886f53e7c12. You can pull that in.

In many cases, it makes sense to keep the folder zipped up if the data are large. There are also R tolls like `unz` that allow you to load data within a zipped directory. But in your case, the data files in the zip directory are quite small and it also contains codebooks and questionnaires that it would be nice to access, so I went ahead and unzipped it and then used the `read_dta` function in the `haven` library to read in the data. 

It looks good now. One frustrating thing about the Pew data is that the variable names are all just numbers like "qc15f" which can require a lot of cross-referencing with the codebook and questionnaire in the initial re-coding phase.
